spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentit?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Moscow&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Europe/Moscow

server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG
    com.rentit: INFO