spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentit?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG
    com.rentit: DEBUG 

debezium:
  mysql:
    hostname: ${MYSQL_HOST:localhost}
    port: ${MYSQL_PORT:3306}
    user: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    serverId: ${MYSQL_SERVER_ID:184054}
    topicPrefix: ${DEBEZIUM_TOPIC_PREFIX:rentit}
    database: ${MYSQL_DATABASE:rentit}
    tableIncludeList: ${DEBEZIUM_TABLE_INCLUDE_LIST:rentit.items,rentit.rentals}

    offsetFile: ${DEBEZIUM_OFFSET_FILE:C:\kafka/debezium/debezium-data/offsets.dat}
    historyFile: ${DEBEZIUM_HISTORY_FILE:C:\kafka/debezium/debezium-data/schema-history.dat}
    snapshotMode: ${DEBEZIUM_SNAPSHOT_MODE:initial}
    connectionTimeZone: ${DEBEZIUM_CONNECTION_TIMEZONE:UTC}
    serverTimezone: ${DEBEZIUM_SERVER_TIMEZONE:UTC}

kafka:
  topics:
    topics:
      RENTAL_CREATED: RENTALS_CREATED
      RENTALS_UPDATED: RENTALS_UPDATED
      ITEM_CREATED: ITEM_CREATED