spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentit_users?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  cloud:
    compatibility-verifier.enabled: false

logging:
  level:
    org.springframework.security: INFO
    com.rentit.user: DEBUG