server:
  port: 8078

jwt:
  secret: ${JWT_SECRET:your-very-long-and-secure-secret}
  expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG